//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID_Ticket { get; set; }
        public Nullable<System.DateTime> DateTime_of_Sell { get; set; }
        public decimal Price { get; set; }
        public int ID_Session { get; set; }
        public Nullable<int> ID_employee { get; set; }
        public int ID_Seats { get; set; }
        public bool Sell { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Seats Seats { get; set; }
        public virtual Session Session { get; set; }
    }
}
